export const serviceMeta = {
  water: { name: 'Вода', accent: 'cyan' },
  gas: { name: 'Газ', accent: 'amber' },
  electricity: { name: 'Электричество', accent: 'yellow' },
  heating: { name: 'Отопление', accent: 'rose' },
  maintenance: { name: 'Содержание жилья', accent: 'blue' },
};

export const initialStore = {
  users: [
    {
      id: 'payer-1',
      role: 'payer',
      name: 'Ирина Волкова',
      email: 'payer@demo.ru',
      password: 'demo',
      phone: '+7 900 123-45-67',
      accountId: 'acc-1',
    },
    {
      id: 'employee-1',
      role: 'employee',
      name: 'Антон Соколов',
      email: 'employee@demo.ru',
      password: 'demo',
      position: 'Специалист абонентского отдела',
    },
  ],
  accounts: [
    {
      id: 'acc-1',
      number: '407900000001',
      ownerName: 'Ирина Волкова',
      address: 'г. Казань, ул. Светлая, 18',
    },
    {
      id: 'acc-2',
      number: '407900000002',
      ownerName: 'Демо-абонент',
      address: 'г. Казань, ул. Озерная, 6',
    },
  ],
  receipts: [
    {
      id: 'rcp-1',
      accountId: 'acc-1',
      period: 'Январь 2026',
      service: 'water',
      amount: 1420,
      status: 'paid',
      dueDate: '2026-02-10',
      paidAt: '2026-02-04',
      method: 'СБП',
    },
    {
      id: 'rcp-2',
      accountId: 'acc-1',
      period: 'Январь 2026',
      service: 'electricity',
      amount: 2380,
      status: 'paid',
      dueDate: '2026-02-10',
      paidAt: '2026-02-06',
      method: 'МИР',
    },
    {
      id: 'rcp-3',
      accountId: 'acc-1',
      period: 'Февраль 2026',
      service: 'gas',
      amount: 960,
      status: 'unpaid',
      dueDate: '2026-03-10',
      paidAt: null,
      method: null,
    },
    {
      id: 'rcp-4',
      accountId: 'acc-1',
      period: 'Март 2026',
      service: 'maintenance',
      amount: 4180,
      status: 'unpaid',
      dueDate: '2026-04-10',
      paidAt: null,
      method: null,
    },
    {
      id: 'rcp-5',
      accountId: 'acc-1',
      period: 'Март 2026',
      service: 'water',
      amount: 1510,
      status: 'unpaid',
      dueDate: '2026-04-10',
      paidAt: null,
      method: null,
    },
    {
      id: 'rcp-6',
      accountId: 'acc-2',
      period: 'Январь 2026',
      service: 'water',
      amount: 1110,
      status: 'paid',
      dueDate: '2026-02-10',
      paidAt: '2026-02-02',
      method: 'СБП',
    },
    {
      id: 'rcp-7',
      accountId: 'acc-2',
      period: 'Февраль 2026',
      service: 'gas',
      amount: 870,
      status: 'paid',
      dueDate: '2026-03-10',
      paidAt: '2026-03-08',
      method: 'МИР',
    },
  ],
  payments: [
    { id: 'pay-1', receiptId: 'rcp-1', method: 'СБП', paidAt: '2026-02-04', amount: 1420 },
    { id: 'pay-2', receiptId: 'rcp-2', method: 'МИР', paidAt: '2026-02-06', amount: 2380 },
    { id: 'pay-3', receiptId: 'rcp-6', method: 'СБП', paidAt: '2026-02-02', amount: 1110 },
    { id: 'pay-4', receiptId: 'rcp-7', method: 'МИР', paidAt: '2026-03-08', amount: 870 },
  ],
};

export function getFreshStore() {
  return structuredClone(initialStore);
}
